insert into celebrities (id, name, height, weight, networth) values (1, 'Lockwood', 5.2, 51.8, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (2, 'Lynna', 5.2, 85.5, 'Bolivar');
insert into celebrities (id, name, height, weight, networth) values (3, 'Agnes', 6.2, 40.9, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (4, 'Marcy', 5.9, 52.4, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (5, 'Nessie', 7.0, 81.0, 'Rial');
insert into celebrities (id, name, height, weight, networth) values (6, 'Hurleigh', 5.2, 81.5, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (7, 'Berny', 6.3, 45.9, 'Rupee');
insert into celebrities (id, name, height, weight, networth) values (8, 'Doloritas', 6.0, 84.8, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (9, 'Mandi', 6.7, 52.8, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (10, 'Christen', 6.4, 49.7, 'Gourde');
insert into celebrities (id, name, height, weight, networth) values (11, 'Alistair', 5.7, 41.0, 'Pound');
insert into celebrities (id, name, height, weight, networth) values (12, 'Rozalin', 5.5, 79.4, 'Tenge');
insert into celebrities (id, name, height, weight, networth) values (13, 'Mira', 6.3, 58.8, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (14, 'Lyndsay', 6.7, 98.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (15, 'Cathi', 5.6, 64.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (16, 'Kellsie', 5.5, 69.6, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (17, 'Roxine', 5.4, 47.5, 'Litas');
insert into celebrities (id, name, height, weight, networth) values (18, 'Norbert', 5.3, 69.4, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (19, 'Birgitta', 5.6, 99.0, 'Rand');
insert into celebrities (id, name, height, weight, networth) values (20, 'Maggie', 5.9, 48.8, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (21, 'Josee', 5.5, 92.2, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (22, 'Kendra', 6.6, 99.2, 'Hryvnia');
insert into celebrities (id, name, height, weight, networth) values (23, 'Afton', 6.5, 95.5, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (24, 'Derril', 6.5, 75.6, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (25, 'Rory', 6.0, 55.5, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (26, 'Arvin', 5.5, 36.1, 'Litas');
insert into celebrities (id, name, height, weight, networth) values (27, 'Amelita', 5.5, 98.5, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (28, 'Trude', 6.8, 98.7, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (29, 'Erhart', 5.6, 33.4, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (30, 'Beilul', 5.3, 86.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (31, 'Aile', 5.7, 78.1, 'Marka');
insert into celebrities (id, name, height, weight, networth) values (32, 'Leslie', 5.6, 99.1, 'Dong');
insert into celebrities (id, name, height, weight, networth) values (33, 'Benn', 5.5, 91.4, 'Boliviano');
insert into celebrities (id, name, height, weight, networth) values (34, 'Gavan', 5.3, 88.1, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (35, 'Giffard', 5.7, 74.6, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (36, 'Kenton', 5.3, 57.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (37, 'Cristine', 5.6, 81.2, 'Tenge');
insert into celebrities (id, name, height, weight, networth) values (38, 'Reba', 5.8, 61.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (39, 'Darbie', 5.2, 81.3, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (40, 'Doria', 5.8, 65.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (41, 'Valery', 5.1, 79.4, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (42, 'Victor', 6.6, 72.1, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (43, 'Agnola', 5.4, 58.4, 'Rial');
insert into celebrities (id, name, height, weight, networth) values (44, 'Victoria', 5.1, 47.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (45, 'Buffy', 5.6, 94.9, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (46, 'West', 5.9, 32.0, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (47, 'Lorianne', 5.5, 58.7, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (48, 'Gena', 6.7, 57.3, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (49, 'Olivier', 6.6, 86.3, 'Naira');
insert into celebrities (id, name, height, weight, networth) values (50, 'Deny', 6.6, 99.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (51, 'Sherilyn', 6.8, 81.5, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (52, 'Kelley', 6.0, 98.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (53, 'Reeba', 5.9, 62.0, 'Real');
insert into celebrities (id, name, height, weight, networth) values (54, 'Luce', 5.0, 70.2, 'Shekel');
insert into celebrities (id, name, height, weight, networth) values (55, 'Craig', 5.2, 57.1, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (56, 'Sacha', 6.9, 53.1, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (57, 'Kamila', 5.2, 70.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (58, 'Yule', 6.8, 33.1, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (59, 'Janna', 5.6, 87.1, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (60, 'Bary', 5.2, 56.0, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (61, 'Aleece', 6.4, 33.1, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (62, 'Merell', 6.4, 81.0, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (63, 'Shawna', 6.3, 97.3, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (64, 'Gracie', 5.7, 81.2, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (65, 'Laughton', 6.8, 80.7, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (66, 'Marion', 6.4, 52.6, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (67, 'Germana', 6.7, 30.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (68, 'Fonz', 5.7, 94.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (69, 'Farrel', 5.2, 67.7, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (70, 'Freeland', 5.2, 46.1, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (71, 'Hubie', 6.6, 51.0, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (72, 'Vyky', 5.6, 39.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (73, 'Igor', 6.0, 80.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (74, 'Glynda', 5.3, 50.2, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (75, 'Derward', 6.0, 50.1, 'Shilling');
insert into celebrities (id, name, height, weight, networth) values (76, 'Aloisia', 6.8, 75.8, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (77, 'Gladi', 6.8, 60.0, 'Kyat');
insert into celebrities (id, name, height, weight, networth) values (78, 'Valentina', 5.5, 99.2, 'Pound');
insert into celebrities (id, name, height, weight, networth) values (79, 'Darbie', 5.6, 48.1, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (80, 'Sterne', 6.9, 56.5, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (81, 'Audry', 6.4, 56.4, 'Lempira');
insert into celebrities (id, name, height, weight, networth) values (82, 'Saleem', 6.5, 35.3, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (83, 'Betsy', 5.6, 66.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (84, 'Fonzie', 6.9, 71.3, 'Hryvnia');
insert into celebrities (id, name, height, weight, networth) values (85, 'Orion', 6.1, 62.7, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (86, 'Judon', 5.3, 70.9, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (87, 'Mirabelle', 6.3, 87.9, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (88, 'Christy', 5.4, 70.1, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (89, 'Rubetta', 5.7, 72.2, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (90, 'Julius', 6.8, 61.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (91, 'Vincents', 5.3, 39.7, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (92, 'Paulita', 5.7, 72.6, 'Real');
insert into celebrities (id, name, height, weight, networth) values (93, 'Mickey', 6.3, 95.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (94, 'Ellette', 5.4, 65.2, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (95, 'Lynne', 5.8, 58.8, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (96, 'Fanny', 5.9, 70.4, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (97, 'Hedy', 5.8, 62.7, 'Franc');
insert into celebrities (id, name, height, weight, networth) values (98, 'Lynsey', 5.3, 90.2, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (99, 'Sybyl', 5.5, 53.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (100, 'Vania', 6.4, 50.9, 'Colon');
insert into celebrities (id, name, height, weight, networth) values (101, 'Ashly', 5.5, 85.8, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (102, 'Dominga', 5.8, 83.4, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (103, 'Ewart', 6.3, 34.4, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (104, 'Alasdair', 6.8, 71.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (105, 'Dionis', 6.8, 48.5, 'Real');
insert into celebrities (id, name, height, weight, networth) values (106, 'Julita', 5.4, 98.7, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (107, 'Sherwood', 6.0, 95.0, 'Tugrik');
insert into celebrities (id, name, height, weight, networth) values (108, 'Stormi', 6.1, 77.8, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (109, 'Korella', 5.4, 47.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (110, 'Fulton', 6.1, 51.4, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (111, 'Aloysia', 5.1, 98.4, 'Shekel');
insert into celebrities (id, name, height, weight, networth) values (112, 'Beltran', 6.5, 78.3, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (113, 'Melina', 5.3, 65.1, 'Hryvnia');
insert into celebrities (id, name, height, weight, networth) values (114, 'Merv', 6.1, 45.3, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (115, 'Emmey', 5.7, 49.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (116, 'Hinda', 5.1, 96.2, 'Dinar');
insert into celebrities (id, name, height, weight, networth) values (117, 'Megan', 5.2, 40.6, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (118, 'Charil', 5.8, 95.6, 'Real');
insert into celebrities (id, name, height, weight, networth) values (119, 'Antoine', 6.7, 44.2, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (120, 'Katey', 5.6, 51.4, 'Kuna');
insert into celebrities (id, name, height, weight, networth) values (121, 'Ailis', 6.4, 81.3, 'Afghani');
insert into celebrities (id, name, height, weight, networth) values (122, 'Gale', 5.5, 91.3, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (123, 'Alejandra', 5.7, 99.4, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (124, 'Otis', 5.7, 30.1, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (125, 'Kandy', 6.5, 80.2, 'Ariary');
insert into celebrities (id, name, height, weight, networth) values (126, 'Eric', 6.8, 74.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (127, 'Gordie', 5.4, 41.8, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (128, 'Ruddy', 5.3, 91.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (129, 'Rozamond', 5.4, 41.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (130, 'Hattie', 5.5, 72.2, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (131, 'Alvinia', 6.9, 80.2, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (132, 'Ethelda', 6.4, 41.5, 'Escudo');
insert into celebrities (id, name, height, weight, networth) values (133, 'Yetta', 5.5, 93.1, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (134, 'Gillian', 5.3, 89.6, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (135, 'Benny', 6.7, 48.0, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (136, 'Amelina', 5.5, 60.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (137, 'Homerus', 5.4, 57.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (138, 'Jarred', 5.9, 84.0, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (139, 'Bobina', 6.3, 59.4, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (140, 'Colet', 6.7, 31.2, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (141, 'Dilan', 5.2, 45.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (142, 'Celine', 5.9, 67.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (143, 'Chrissie', 5.0, 90.2, 'Afghani');
insert into celebrities (id, name, height, weight, networth) values (144, 'Eleanora', 6.4, 84.1, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (145, 'Annabelle', 5.6, 54.0, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (146, 'Darrin', 6.4, 86.6, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (147, 'Menard', 6.8, 79.6, 'Dong');
insert into celebrities (id, name, height, weight, networth) values (148, 'Violet', 5.0, 47.6, 'Cedi');
insert into celebrities (id, name, height, weight, networth) values (149, 'Astrix', 5.0, 89.5, 'Bolivar');
insert into celebrities (id, name, height, weight, networth) values (150, 'Marysa', 5.6, 96.2, 'Afghani');
insert into celebrities (id, name, height, weight, networth) values (151, 'Horten', 5.6, 94.0, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (152, 'Cyrillus', 6.4, 33.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (153, 'Jon', 5.3, 73.6, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (154, 'Xavier', 6.4, 66.3, 'Kwanza');
insert into celebrities (id, name, height, weight, networth) values (155, 'Elliot', 6.5, 71.5, 'Pound');
insert into celebrities (id, name, height, weight, networth) values (156, 'Ambrosius', 6.8, 96.0, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (157, 'Elvira', 6.7, 66.5, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (158, 'Lynsey', 5.5, 49.2, 'Dong');
insert into celebrities (id, name, height, weight, networth) values (159, 'Burty', 5.2, 62.9, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (160, 'Tomasina', 6.1, 68.1, 'Vatu');
insert into celebrities (id, name, height, weight, networth) values (161, 'Melodee', 5.3, 42.7, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (162, 'Tristan', 5.7, 56.4, 'Real');
insert into celebrities (id, name, height, weight, networth) values (163, 'Marcella', 5.9, 41.9, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (164, 'Raynor', 5.2, 44.2, 'Kwacha');
insert into celebrities (id, name, height, weight, networth) values (165, 'Nichol', 6.9, 30.4, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (166, 'Ingaberg', 5.9, 89.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (167, 'Bobby', 6.8, 94.3, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (168, 'Shannan', 5.7, 99.3, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (169, 'Calida', 5.0, 64.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (170, 'Linda', 6.1, 36.0, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (171, 'Dacy', 5.6, 89.2, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (172, 'Kirby', 5.1, 53.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (173, 'Shannan', 5.7, 87.8, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (174, 'Tuckie', 5.2, 53.1, 'Real');
insert into celebrities (id, name, height, weight, networth) values (175, 'Graham', 6.9, 99.3, 'Real');
insert into celebrities (id, name, height, weight, networth) values (176, 'Lyndsie', 5.8, 32.8, 'Real');
insert into celebrities (id, name, height, weight, networth) values (177, 'Glenn', 6.5, 63.8, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (178, 'Morna', 5.8, 77.8, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (179, 'Broddie', 6.6, 92.1, 'Kwanza');
insert into celebrities (id, name, height, weight, networth) values (180, 'Julia', 6.0, 67.4, 'Dong');
insert into celebrities (id, name, height, weight, networth) values (181, 'Meaghan', 5.0, 52.1, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (182, 'Zelda', 6.7, 97.6, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (183, 'Eudora', 6.2, 65.6, 'Kyat');
insert into celebrities (id, name, height, weight, networth) values (184, 'Arvy', 5.3, 71.4, 'Real');
insert into celebrities (id, name, height, weight, networth) values (185, 'Waldon', 6.8, 41.3, 'Real');
insert into celebrities (id, name, height, weight, networth) values (186, 'Kellina', 5.8, 76.6, 'Real');
insert into celebrities (id, name, height, weight, networth) values (187, 'Bernie', 5.3, 82.0, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (188, 'Erin', 6.2, 64.0, 'Shilling');
insert into celebrities (id, name, height, weight, networth) values (189, 'Hebert', 6.8, 74.2, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (190, 'Davy', 5.8, 62.2, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (191, 'Doyle', 6.4, 74.8, 'Bolivar');
insert into celebrities (id, name, height, weight, networth) values (192, 'Camella', 6.4, 55.8, 'Krone');
insert into celebrities (id, name, height, weight, networth) values (193, 'Frederick', 5.3, 77.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (194, 'Godfrey', 6.8, 99.4, 'Pound');
insert into celebrities (id, name, height, weight, networth) values (195, 'Tildi', 6.4, 42.0, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (196, 'Karena', 5.1, 91.5, 'Rial');
insert into celebrities (id, name, height, weight, networth) values (197, 'Eolande', 5.4, 79.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (198, 'Anatole', 5.1, 63.4, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (199, 'Free', 5.5, 90.3, 'Pound');
insert into celebrities (id, name, height, weight, networth) values (200, 'Neille', 5.8, 53.7, 'Kip');
insert into celebrities (id, name, height, weight, networth) values (201, 'Odetta', 5.8, 65.3, 'Quetzal');
insert into celebrities (id, name, height, weight, networth) values (202, 'Timoteo', 6.2, 71.6, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (203, 'Burl', 5.7, 64.3, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (204, 'Chloette', 6.5, 74.3, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (205, 'Jard', 6.7, 31.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (206, 'Tamas', 5.2, 53.1, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (207, 'Corena', 6.6, 93.3, 'Tugrik');
insert into celebrities (id, name, height, weight, networth) values (208, 'Neilla', 5.4, 54.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (209, 'Alfonso', 5.6, 69.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (210, 'Dukie', 6.2, 51.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (211, 'Toby', 6.1, 54.4, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (212, 'Lesley', 6.7, 55.1, 'Lev');
insert into celebrities (id, name, height, weight, networth) values (213, 'Chadwick', 6.4, 77.9, 'Baht');
insert into celebrities (id, name, height, weight, networth) values (214, 'Emanuel', 6.8, 80.2, 'Baht');
insert into celebrities (id, name, height, weight, networth) values (215, 'Trever', 5.0, 41.4, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (216, 'Alberik', 6.1, 65.5, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (217, 'Cleve', 5.1, 47.9, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (218, 'Terrence', 6.5, 92.7, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (219, 'Denis', 5.1, 33.3, 'Metical');
insert into celebrities (id, name, height, weight, networth) values (220, 'Maurizio', 6.9, 42.7, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (221, 'Hollyanne', 5.6, 63.6, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (222, 'Judas', 5.2, 81.1, 'Tenge');
insert into celebrities (id, name, height, weight, networth) values (223, 'Ailene', 6.6, 31.8, 'Dirham');
insert into celebrities (id, name, height, weight, networth) values (224, 'Kattie', 5.1, 98.6, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (225, 'Laetitia', 5.5, 33.7, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (226, 'Marlon', 5.2, 69.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (227, 'Edeline', 5.9, 30.6, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (228, 'Filberto', 5.3, 79.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (229, 'Hadleigh', 6.2, 41.4, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (230, 'Franklin', 5.1, 76.9, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (231, 'Reade', 5.9, 84.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (232, 'Marius', 5.5, 93.9, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (233, 'Berkley', 6.3, 52.8, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (234, 'Peyton', 7.0, 61.2, 'Leu');
insert into celebrities (id, name, height, weight, networth) values (235, 'Cello', 5.1, 69.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (236, 'Ronnica', 5.7, 42.5, 'Baht');
insert into celebrities (id, name, height, weight, networth) values (237, 'Nil', 6.0, 46.6, 'Real');
insert into celebrities (id, name, height, weight, networth) values (238, 'Antonella', 5.7, 87.1, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (239, 'Lila', 5.1, 61.5, 'Hryvnia');
insert into celebrities (id, name, height, weight, networth) values (240, 'Marvin', 6.3, 35.1, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (241, 'Guillermo', 5.8, 76.9, 'Krone');
insert into celebrities (id, name, height, weight, networth) values (242, 'Franni', 6.4, 46.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (243, 'Leesa', 6.5, 64.9, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (244, 'Griffith', 5.5, 97.5, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (245, 'Crosby', 6.7, 88.3, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (246, 'Cordy', 6.5, 32.9, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (247, 'Matthaeus', 5.1, 40.7, 'Guilder');
insert into celebrities (id, name, height, weight, networth) values (248, 'Ollie', 6.7, 87.7, 'Som');
insert into celebrities (id, name, height, weight, networth) values (249, 'Randi', 6.1, 33.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (250, 'Jean', 6.0, 33.2, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (251, 'Sherlocke', 6.6, 35.0, 'Franc');
insert into celebrities (id, name, height, weight, networth) values (252, 'Stinky', 5.9, 48.9, 'Naira');
insert into celebrities (id, name, height, weight, networth) values (253, 'Doloritas', 5.3, 55.5, 'Baht');
insert into celebrities (id, name, height, weight, networth) values (254, 'Steward', 5.7, 55.3, 'Real');
insert into celebrities (id, name, height, weight, networth) values (255, 'Shandee', 6.8, 84.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (256, 'Corrina', 6.4, 67.4, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (257, 'Demeter', 6.3, 58.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (258, 'Caz', 6.0, 36.4, 'Boliviano');
insert into celebrities (id, name, height, weight, networth) values (259, 'Ashleigh', 6.4, 66.2, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (260, 'Allix', 5.9, 93.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (261, 'Alva', 5.1, 65.3, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (262, 'Allan', 5.8, 98.3, 'Lempira');
insert into celebrities (id, name, height, weight, networth) values (263, 'Ethelyn', 6.9, 38.0, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (264, 'Anallise', 6.0, 52.8, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (265, 'Fredericka', 5.4, 81.3, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (266, 'Carlin', 6.4, 70.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (267, 'Bev', 6.1, 86.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (268, 'Adeline', 6.5, 43.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (269, 'Mommy', 6.4, 84.5, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (270, 'Emma', 5.6, 51.2, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (271, 'Christopher', 6.7, 87.3, 'Rand');
insert into celebrities (id, name, height, weight, networth) values (272, 'Ilise', 6.1, 45.1, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (273, 'Mattie', 6.9, 73.7, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (274, 'Bonnie', 5.1, 77.6, 'Shilling');
insert into celebrities (id, name, height, weight, networth) values (275, 'Terrill', 5.5, 90.6, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (276, 'Max', 6.0, 68.9, 'Baht');
insert into celebrities (id, name, height, weight, networth) values (277, 'Isaac', 6.7, 58.6, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (278, 'Kylie', 6.2, 33.1, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (279, 'Joel', 6.2, 80.1, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (280, 'Cozmo', 6.2, 75.9, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (281, 'Conn', 6.0, 78.9, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (282, 'Daryle', 5.1, 70.2, 'Leu');
insert into celebrities (id, name, height, weight, networth) values (283, 'Marlane', 6.8, 84.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (284, 'Barbey', 6.0, 52.7, 'Ariary');
insert into celebrities (id, name, height, weight, networth) values (285, 'Merna', 5.8, 80.5, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (286, 'Bordie', 5.1, 77.0, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (287, 'Cosette', 6.1, 81.6, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (288, 'Nananne', 6.4, 75.9, 'Kuna');
insert into celebrities (id, name, height, weight, networth) values (289, 'Godfrey', 5.6, 74.6, 'Rial');
insert into celebrities (id, name, height, weight, networth) values (290, 'Adelaide', 5.1, 81.9, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (291, 'Julio', 6.0, 70.2, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (292, 'Gasparo', 6.0, 71.9, 'Shilling');
insert into celebrities (id, name, height, weight, networth) values (293, 'Lotta', 5.7, 46.2, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (294, 'Nomi', 6.8, 58.7, 'Pound');
insert into celebrities (id, name, height, weight, networth) values (295, 'Isak', 5.3, 60.5, 'Rial');
insert into celebrities (id, name, height, weight, networth) values (296, 'Lorita', 6.3, 36.8, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (297, 'Bartholomeo', 5.9, 58.0, 'Shilling');
insert into celebrities (id, name, height, weight, networth) values (298, 'Tilly', 5.3, 47.3, 'Dinar');
insert into celebrities (id, name, height, weight, networth) values (299, 'Webb', 5.5, 60.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (300, 'Virginia', 5.2, 92.2, 'Baht');
insert into celebrities (id, name, height, weight, networth) values (301, 'Christoph', 5.6, 52.9, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (302, 'Wayland', 6.5, 52.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (303, 'Virgie', 6.1, 41.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (304, 'Dorothee', 5.9, 55.6, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (305, 'Kasey', 6.9, 67.1, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (306, 'Cecilla', 6.8, 81.1, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (307, 'Concettina', 5.9, 59.6, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (308, 'Bonnibelle', 5.1, 33.3, 'Baht');
insert into celebrities (id, name, height, weight, networth) values (309, 'Raymund', 5.7, 93.2, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (310, 'Cory', 7.0, 33.1, 'Real');
insert into celebrities (id, name, height, weight, networth) values (311, 'Sada', 6.5, 44.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (312, 'Evelin', 5.2, 46.1, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (313, 'Thibaut', 6.5, 81.5, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (314, 'Mildrid', 6.6, 59.7, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (315, 'Abran', 6.6, 70.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (316, 'Aharon', 6.3, 86.7, 'Shilling');
insert into celebrities (id, name, height, weight, networth) values (317, 'Elwin', 5.9, 90.9, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (318, 'Florida', 5.3, 43.3, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (319, 'Caroljean', 6.8, 75.5, 'Hryvnia');
insert into celebrities (id, name, height, weight, networth) values (320, 'Jonell', 6.6, 86.2, 'Kuna');
insert into celebrities (id, name, height, weight, networth) values (321, 'Zackariah', 5.9, 33.3, 'Dinar');
insert into celebrities (id, name, height, weight, networth) values (322, 'Erika', 6.8, 49.2, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (323, 'Allie', 6.2, 67.8, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (324, 'Sophia', 6.5, 74.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (325, 'Elysia', 6.9, 52.3, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (326, 'Gwenette', 5.5, 37.0, 'Tugrik');
insert into celebrities (id, name, height, weight, networth) values (327, 'Nadeen', 5.7, 37.8, 'Tenge');
insert into celebrities (id, name, height, weight, networth) values (328, 'Fania', 6.7, 85.5, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (329, 'Thomasina', 5.5, 68.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (330, 'Coral', 5.7, 31.0, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (331, 'Gladys', 6.4, 79.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (332, 'Aprilette', 6.2, 72.3, 'Som');
insert into celebrities (id, name, height, weight, networth) values (333, 'Huntlee', 5.2, 36.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (334, 'Teodor', 5.9, 58.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (335, 'Allix', 6.9, 92.8, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (336, 'Carlyle', 5.6, 55.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (337, 'Salem', 5.2, 42.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (338, 'Jessie', 6.4, 34.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (339, 'Tony', 5.5, 79.5, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (340, 'Augustin', 6.3, 91.0, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (341, 'Kliment', 5.2, 60.0, 'Ariary');
insert into celebrities (id, name, height, weight, networth) values (342, 'Yorgos', 6.1, 84.7, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (343, 'Panchito', 6.0, 51.9, 'Litas');
insert into celebrities (id, name, height, weight, networth) values (344, 'Chan', 5.0, 70.7, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (345, 'Lanni', 6.4, 58.7, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (346, 'Jayme', 6.2, 88.1, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (347, 'Ken', 5.7, 73.8, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (348, 'Ronica', 5.1, 32.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (349, 'Nealon', 5.3, 34.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (350, 'Pierrette', 5.5, 89.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (351, 'Godfrey', 6.6, 89.8, 'Rial');
insert into celebrities (id, name, height, weight, networth) values (352, 'Karlotte', 6.9, 71.3, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (353, 'Carmela', 6.0, 61.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (354, 'Madelaine', 5.3, 57.3, 'Ringgit');
insert into celebrities (id, name, height, weight, networth) values (355, 'Gordan', 5.7, 78.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (356, 'Netta', 5.6, 98.2, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (357, 'Gloriane', 5.0, 81.7, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (358, 'Jorgan', 6.0, 70.4, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (359, 'Christina', 6.0, 69.5, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (360, 'Persis', 5.4, 75.8, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (361, 'Reagen', 5.8, 52.9, 'Dirham');
insert into celebrities (id, name, height, weight, networth) values (362, 'Tammie', 5.2, 52.2, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (363, 'Doris', 5.8, 37.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (364, 'Doreen', 6.5, 56.6, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (365, 'Hillie', 5.6, 36.8, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (366, 'Steffen', 6.9, 46.4, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (367, 'Nanon', 5.7, 93.4, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (368, 'Darlleen', 5.7, 98.7, 'Real');
insert into celebrities (id, name, height, weight, networth) values (369, 'Brendin', 6.8, 80.7, 'Franc');
insert into celebrities (id, name, height, weight, networth) values (370, 'Willabella', 6.7, 83.6, 'Denar');
insert into celebrities (id, name, height, weight, networth) values (371, 'Leonid', 5.7, 37.3, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (372, 'Lyda', 6.6, 41.5, 'Rupee');
insert into celebrities (id, name, height, weight, networth) values (373, 'Shaw', 6.7, 90.2, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (374, 'Velvet', 6.8, 94.6, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (375, 'Bobbye', 5.1, 69.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (376, 'Jaynell', 6.1, 79.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (377, 'Vinnie', 5.4, 35.5, 'Real');
insert into celebrities (id, name, height, weight, networth) values (378, 'Blanch', 5.7, 61.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (379, 'Deborah', 5.5, 94.3, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (380, 'Adelheid', 6.0, 74.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (381, 'Rosalinda', 5.1, 43.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (382, 'Luis', 6.4, 57.3, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (383, 'Carin', 5.3, 97.5, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (384, 'Karon', 6.9, 45.1, 'Dalasi');
insert into celebrities (id, name, height, weight, networth) values (385, 'Valle', 5.8, 48.2, 'Forint');
insert into celebrities (id, name, height, weight, networth) values (386, 'Bailey', 6.1, 91.4, 'Real');
insert into celebrities (id, name, height, weight, networth) values (387, 'Pippa', 5.1, 95.2, 'Kina');
insert into celebrities (id, name, height, weight, networth) values (388, 'Elsy', 5.2, 61.3, 'Lempira');
insert into celebrities (id, name, height, weight, networth) values (389, 'Eleanor', 5.2, 70.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (390, 'Lurlene', 5.2, 97.8, 'Dinar');
insert into celebrities (id, name, height, weight, networth) values (391, 'Sheppard', 5.7, 84.0, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (392, 'Melesa', 6.0, 59.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (393, 'Hart', 6.8, 62.6, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (394, 'Brion', 5.9, 49.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (395, 'Creight', 6.8, 88.8, 'Lev');
insert into celebrities (id, name, height, weight, networth) values (396, 'Almeria', 5.0, 94.9, 'Dinar');
insert into celebrities (id, name, height, weight, networth) values (397, 'Othella', 5.5, 65.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (398, 'Petronilla', 6.5, 56.3, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (399, 'Dall', 5.4, 76.0, 'Rand');
insert into celebrities (id, name, height, weight, networth) values (400, 'Roseline', 5.1, 40.6, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (401, 'Arni', 6.6, 57.1, 'Lempira');
insert into celebrities (id, name, height, weight, networth) values (402, 'See', 5.1, 68.2, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (403, 'Bron', 6.1, 82.7, 'Dram');
insert into celebrities (id, name, height, weight, networth) values (404, 'Rusty', 6.7, 45.5, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (405, 'Bridget', 5.5, 85.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (406, 'Shanan', 5.9, 70.5, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (407, 'Griz', 5.9, 35.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (408, 'Arnaldo', 6.5, 43.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (409, 'Nathanil', 6.0, 43.6, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (410, 'Camilla', 5.8, 88.6, 'Dram');
insert into celebrities (id, name, height, weight, networth) values (411, 'Ursala', 5.2, 70.1, 'Tenge');
insert into celebrities (id, name, height, weight, networth) values (412, 'Coralie', 5.1, 73.5, 'Som');
insert into celebrities (id, name, height, weight, networth) values (413, 'Nevsa', 5.2, 53.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (414, 'Ashlin', 5.2, 67.2, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (415, 'Suzanna', 5.5, 31.8, 'Balboa');
insert into celebrities (id, name, height, weight, networth) values (416, 'Celle', 6.5, 31.9, 'Real');
insert into celebrities (id, name, height, weight, networth) values (417, 'Sandi', 5.6, 99.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (418, 'Mary', 5.6, 67.4, 'Dirham');
insert into celebrities (id, name, height, weight, networth) values (419, 'Stillman', 5.7, 96.4, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (420, 'Hamil', 5.0, 51.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (421, 'Clint', 5.9, 72.5, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (422, 'Edvard', 5.7, 70.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (423, 'Benyamin', 6.9, 86.7, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (424, 'Osmund', 6.8, 78.8, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (425, 'Effie', 6.9, 82.4, 'Koruna');
insert into celebrities (id, name, height, weight, networth) values (426, 'Nixie', 6.1, 57.2, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (427, 'Harald', 6.3, 31.0, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (428, 'Jewelle', 6.0, 99.0, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (429, 'Yuri', 5.2, 88.6, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (430, 'Petronille', 5.5, 48.3, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (431, 'Minor', 5.6, 43.6, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (432, 'Herc', 6.2, 91.1, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (433, 'Stanleigh', 5.9, 39.8, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (434, 'Margalo', 6.6, 59.2, 'Rupee');
insert into celebrities (id, name, height, weight, networth) values (435, 'Victoria', 6.8, 31.6, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (436, 'Dunc', 6.3, 41.6, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (437, 'Godwin', 6.1, 71.1, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (438, 'Gabriel', 6.4, 44.5, 'Real');
insert into celebrities (id, name, height, weight, networth) values (439, 'Michael', 6.4, 82.7, 'Afghani');
insert into celebrities (id, name, height, weight, networth) values (440, 'Lani', 5.7, 40.4, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (441, 'Serge', 6.0, 67.9, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (442, 'Zaccaria', 6.2, 79.4, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (443, 'Joshia', 5.5, 99.7, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (444, 'Johnathon', 5.2, 64.2, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (445, 'Merrilee', 6.6, 86.7, 'Cedi');
insert into celebrities (id, name, height, weight, networth) values (446, 'Ryann', 5.8, 80.0, 'Sol');
insert into celebrities (id, name, height, weight, networth) values (447, 'Barney', 6.7, 55.7, 'Rupee');
insert into celebrities (id, name, height, weight, networth) values (448, 'Chere', 5.1, 84.9, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (449, 'Berty', 6.9, 63.3, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (450, 'Agnella', 5.5, 38.6, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (451, 'Gisele', 5.1, 99.6, 'Quetzal');
insert into celebrities (id, name, height, weight, networth) values (452, 'Lauryn', 6.9, 78.0, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (453, 'Janet', 6.7, 53.2, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (454, 'Millicent', 5.2, 97.9, 'Rupee');
insert into celebrities (id, name, height, weight, networth) values (455, 'Essie', 5.2, 36.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (456, 'Wayland', 5.8, 65.9, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (457, 'Noel', 5.8, 62.5, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (458, 'Merle', 6.9, 66.7, 'Litas');
insert into celebrities (id, name, height, weight, networth) values (459, 'Juliann', 6.4, 60.5, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (460, 'Alexandro', 5.0, 37.7, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (461, 'Hanna', 6.9, 61.1, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (462, 'Cyb', 5.8, 43.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (463, 'Harri', 6.5, 35.6, 'Leu');
insert into celebrities (id, name, height, weight, networth) values (464, 'Gifford', 5.5, 55.4, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (465, 'Marylynne', 5.3, 43.6, 'Quetzal');
insert into celebrities (id, name, height, weight, networth) values (466, 'Ravid', 5.1, 36.8, 'Hryvnia');
insert into celebrities (id, name, height, weight, networth) values (467, 'Jemmy', 5.7, 87.4, 'Shekel');
insert into celebrities (id, name, height, weight, networth) values (468, 'Enrico', 6.1, 54.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (469, 'Alanson', 6.5, 56.9, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (470, 'Les', 6.3, 77.4, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (471, 'Gloriane', 5.4, 45.1, 'Dong');
insert into celebrities (id, name, height, weight, networth) values (472, 'Raimundo', 5.9, 56.7, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (473, 'Ashely', 6.6, 79.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (474, 'Silvie', 6.6, 64.3, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (475, 'Hamid', 6.2, 46.8, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (476, 'Norri', 6.2, 80.7, 'Dollar');
insert into celebrities (id, name, height, weight, networth) values (477, 'Wilhelm', 6.0, 88.1, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (478, 'Sari', 5.4, 53.3, 'Real');
insert into celebrities (id, name, height, weight, networth) values (479, 'Garreth', 5.5, 77.3, 'Hryvnia');
insert into celebrities (id, name, height, weight, networth) values (480, 'Pablo', 6.0, 92.6, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (481, 'Lennie', 6.7, 87.1, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (482, 'Gino', 5.7, 50.0, 'Krona');
insert into celebrities (id, name, height, weight, networth) values (483, 'Raynard', 5.8, 83.0, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (484, 'Elora', 5.2, 54.8, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (485, 'Nolan', 6.7, 95.8, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (486, 'Merrill', 6.3, 78.8, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (487, 'Ardine', 5.5, 44.9, 'Leu');
insert into celebrities (id, name, height, weight, networth) values (488, 'Patrick', 6.3, 99.2, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (489, 'Bo', 6.9, 87.2, 'Zloty');
insert into celebrities (id, name, height, weight, networth) values (490, 'Michaeline', 6.7, 49.9, 'Dinar');
insert into celebrities (id, name, height, weight, networth) values (491, 'Tallou', 5.9, 93.3, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (492, 'Renado', 6.4, 78.9, 'Yuan Renminbi');
insert into celebrities (id, name, height, weight, networth) values (493, 'Arlinda', 5.8, 48.9, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (494, 'Trace', 5.0, 79.1, 'Euro');
insert into celebrities (id, name, height, weight, networth) values (495, 'Alayne', 6.7, 87.7, 'Peso');
insert into celebrities (id, name, height, weight, networth) values (496, 'Louisa', 6.1, 47.6, 'Yen');
insert into celebrities (id, name, height, weight, networth) values (497, 'Gerrie', 5.8, 57.8, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (498, 'Pace', 5.6, 89.6, 'Rupiah');
insert into celebrities (id, name, height, weight, networth) values (499, 'Glenden', 6.1, 58.5, 'Ruble');
insert into celebrities (id, name, height, weight, networth) values (500, 'Nicolea', 5.6, 69.5, 'Cordoba');
